# Generated by Django 4.2.1 on 2023-06-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('SanPham_id', models.AutoField(primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=50)),
                ('GiaTien', models.FloatField()),
                ('Soluonghienco', models.IntegerField()),
                ('ThoigianSD', models.CharField(max_length=50)),
                ('DanhMuc_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.danhmuc')),
            ],
        ),
    ]
